CREATE TABLE clans (
    clan_id SERIAL NOT NULL PRIMARY KEY,
    name VARCHAR(32) NOT NULL,
    tag VARCHAR(8) NOT NULL,
    description TEXT,
    owner INTEGER NOT NULL,
    join_method VARCHAR(64) NOT NULL,
    status VARCHAR(64) NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);